- name: Install Apache web server
  become: true
  apt:
    name: apache2
    state: present
  tags:
    - apache
- name: Start Apache service
  become: true
  service:
    name: apache2
    state: started
  tags:
    - apache---
# tasks file for apache
